2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_setup.py:_flush():67] Configure stats pid to 27584
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_setup.py:_flush():67] Loading settings from C:\Users\praha\.config\wandb\settings
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_setup.py:_flush():67] Loading settings from C:\Users\praha\Documents\IIT madras\Acads\sem 10\introtoDL\A02\da6401-assignment-2\wandb\settings
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\praha\Documents\IIT madras\Acads\sem 10\introtoDL\A02\da6401-assignment-2\wandb\run-20250418_190328-y5pchsy9\logs\debug.log
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\praha\Documents\IIT madras\Acads\sem 10\introtoDL\A02\da6401-assignment-2\wandb\run-20250418_190328-y5pchsy9\logs\debug-internal.log
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_init.py:init():761] calling init triggers
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_init.py:init():784] starting backend
2025-04-18 19:03:28,104 INFO    MainThread:27584 [wandb_init.py:init():788] sending inform_init request
2025-04-18 19:03:28,130 INFO    MainThread:27584 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-18 19:03:28,130 INFO    MainThread:27584 [wandb_init.py:init():798] backend started and connected
2025-04-18 19:03:28,131 INFO    MainThread:27584 [wandb_init.py:init():891] updated telemetry
2025-04-18 19:03:28,194 INFO    MainThread:27584 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-18 19:03:28,603 INFO    MainThread:27584 [wandb_init.py:init():990] starting run threads in backend
2025-04-18 19:03:29,241 INFO    MainThread:27584 [wandb_run.py:_console_start():2375] atexit reg
2025-04-18 19:03:29,241 INFO    MainThread:27584 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-18 19:03:29,242 INFO    MainThread:27584 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-18 19:03:29,242 INFO    MainThread:27584 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-18 19:03:29,246 INFO    MainThread:27584 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-18 19:03:29,271 INFO    MainThread:27584 [wandb_run.py:_config_callback():1261] config_cb None None {'num_conv_layers': 3, 'num_filters': 32, 'filter_size': 3, 'activation': 'ReLU', 'dense_layer_neurons': 128, 'learning_rate': 0.001}
2025-04-18 19:03:29,811 ERROR   MainThread:27584 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\interface\interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\google\protobuf\internal\well_known_types.py", line 195, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\google\protobuf\internal\well_known_types.py", line 268, in FromDatetime
    self.seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-04-18 19:03:29,817 ERROR   MainThread:27584 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\interface\interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\google\protobuf\internal\well_known_types.py", line 195, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\google\protobuf\internal\well_known_types.py", line 268, in FromDatetime
    self.seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-04-18 19:03:29,818 ERROR   MainThread:27584 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\interface\interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\google\protobuf\internal\well_known_types.py", line 195, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "C:\Users\praha\miniconda3\envs\DS\lib\site-packages\google\protobuf\internal\well_known_types.py", line 268, in FromDatetime
    self.seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
